services:
  mongo_db:
    image: mongo:8.0
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
      - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
    volumes:
      - db:/db
  leaderboard:
    depends_on:
      - mongo_db
    build:
      context: ./
      target: dev
    restart: unless-stopped
    env_file: ./.env
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
  db:
