services:
  mongo_db_test:
    image: mongo:6.0.27
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
      - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
  leaderboard_test:
    depends_on:
      - mongo_db_test
    build: 
      context: ./
      target: test
    env_file: 
      - ./.env
      - ./test.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    environment:
      - TARGET=test